### ISSUE TITLE
关于model的问题

### ISSUE THREAD

**Issue by ChrisCatCP** [d80x86/lua-resty-tofu#2]
好像文档里没有讲model/\<name\>.lua
这个model库默认加载的文件的用法是什么...

**Comment by d80x86** [comment]
默认的model是由 `resty.tofu.extend.model` 提供,目前仅支持mysql
如有 `tofu.model('user')` , 会先尝试加载`<应用>/lua/model/user.lua`文件, user.lua 需 return  table. 而model方法会将该table包装成一个model， 也就是相当于继承

``` lua
-- 如有  user.lua 文件
local _M = {}
function _M:get_by_id(id)
    -- ... 
    return tofu.model('user_info').get({user_id = id})
end
return _M
```

现在可以使用 `tofu.model('user').get_by_id(123)` 

注意:调用时区别于常规lua语法, 使用了 `.`点 方式的链式调用风格, 而不是常规的 `:`冒号方式
